### PR TITLE
Most fewest goals and favorite rival methods

### PR DESCRIPTION
**Pull request by the-color-bliu**
ALL_METHOD_EXTRACTIONS

1. Duplicate stat_tracker tests in following classes:
- team_manager
- game_manager
- game_team_manager

2. Create helper methods for following classes:
- team_manager
- game_manager
- game_team_manager

3. Extract all methods into appropriate paths

**Notes/To-do in no particular order:**
- [x] Branch passes rspec, but takes up to 2:30 minutes to pass
- [ ] Game_team_manager and game_manager are now both around 200 lines.
- [ ] Refactoring needs to be done on blocks with averages/divisions using two hashes
- [ ] Modules?

### CODE REVIEW

**Comment by nmking22** [comment]
Looks good! Should we sort out why the rspec is taking so long before we merge this?

**Comment by ETBassist** [comment]
Great work! I agree that we might want to play around with it a bit and see if we can figure out what's up with the test speed, but I'm also fine with just merging it if all the tests are passing

**Review by Todd-Estes — APPROVED** [review]
Good work!

**Review by ETBassist — APPROVED** [review]
Yusss, looks good!

**Comment by nmking22** [comment]
Awesome changes! Merge approved. Thank you Michael Jordan!

**Review by Todd-Estes — APPROVED** [review]

**Pull request merged**
